language: python

install:
  - pip install requests
  - pip install bs4

script: python -m pytest

notifications:
  email:
    - juho.paakkonen@helsinki.fi
  webhooks:
    - http://head.hiit.fi/hooks/fguzu511p3nm8cd9p1b78r3zar
