language: python

install:
  - pip install requests
  - pip install bs4

script: python -m pytest

notifications:
  email:
    recipients:
      - juho.paakkonen@helsinki.fi
  on_success: always
  on_failure: always
