import requests

from bs4 import BeautifulSoup

def parse( url , out ):

    ## ylex seems to be generated by JS.

    return

if __name__ == '__main__':
	parse("http://www.kauppalehti.fi/uutiset/putin-nayttaytyi-julkisuudessa-ilman-juoruja-olisi-tylsaa/pBBPEhQ2?ext=ampparit", file('kauppalehti.txt', 'w'))
