import requests
from bs4 import BeautifulSoup
import processor
from datetime import datetime

def parse( url ):

    r = requests.get( url )

    http_status = r.status_code
    if r.status_code == 404:
        return

    # Kauppalehti seems to be generated by JS.

    return processor.create_dictionary(url, http_status, [''], [''], '', '', '', '', [''], [''])

if __name__ == '__main__':
	parse("http://www.kauppalehti.fi/uutiset/putin-nayttaytyi-julkisuudessa-ilman-juoruja-olisi-tylsaa/pBBPEhQ2?ext=ampparit", file('kauppalehti.txt', 'w'))
