# -*- coding: utf-8 -*-

import requests
from bs4 import BeautifulSoup
import processor
from datetime import datetime

def parse( url ):

    r = requests.get( url )
    if r.status_code == 404:
        processor.create_dictionary(url, r.status_code, [''], [''], '', '', '', '', [''], [''])

    # Kauppalehti seems to be generated by JS.

    return processor.create_dictionary(url, r.status_code, [''], [''], '', '', '', '', [''], [''])

if __name__ == '__main__':
	parse("http://www.kauppalehti.fi/uutiset/putin-nayttaytyi-julkisuudessa-ilman-juoruja-olisi-tylsaa/pBBPEhQ2?ext=ampparit", file('kauppalehti.txt', 'w'))
